#!/usr/bin/env python2
from PIL import Image # PIL  is python-imaging package on debian/ubuntu. See http://en.wikipedia.org/wiki/Python_Imaging_Library
import sys

filename =  sys.argv[1] # '8x16_437.png'
src = Image.open(filename)
name = filename.split("/")[-1][:-4]

print "// autogenerated by mk_mug.py", filename
print "const uint16_t mug_%s[27][27] = {\n   "%name,
for y in range(27):
  print "{", 
  for x in range(27):
    pix = src.getpixel((x,y))
    print "0x%04x,"%((pix[0]>>3)<<10 | (pix[1]>>3)<<5 | (pix[2]>>3)), 
  print "},\n   ",
print "};"
